-- ============================================================
-- Products catalog -> DB. Migrates the catalog out of
-- src/data/products.js so SKUs are managed from admin (add / edit /
-- disable, pricing, gating, rails) with no code deploy. Pricing stays
-- server-authoritative: computeOrderTotals() reads price from HERE by id.
-- Generated by scripts/gen-products-seed.js. Idempotent (re-runnable).
-- ============================================================

create table if not exists products (
  id                 text primary key,
  sku                text unique not null,
  name               text not null,
  dosage             text,
  price              numeric(10,2) not null,
  description        text,
  category           text,
  format             text,
  vial_size          text,
  in_stock           boolean not null default true,
  stock              integer,
  is_kit             boolean not null default false,
  parent_id          text,
  vial_count         integer,
  purity             numeric,
  badge              jsonb,
  mw                 text,
  half_life          text,
  recon_shelf_life   text,
  expiry             text,
  preorder_ship_date text,
  -- gating + rails (new). Fail-safe defaults for ADMIN-added rows: hidden +
  -- most-restrictive until explicitly published. The seed below overrides
  -- these per existing SKU.
  visibility_tier    text not null default 'account_gated'
                       check (visibility_tier in ('public','cohort','account_gated')),
  rail_policy        text not null default 'all'
                       check (rail_policy in ('all','p2p_crypto','zelle_crypto')),
  has_coa            boolean not null default true,
  image_url          text,
  published          boolean not null default false,
  sort_order         integer not null default 100,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists products_visibility_idx on products (visibility_tier) where published;
create index if not exists products_category_idx on products (category);

-- Account allowlist for the account-gated tier (grant/revoke from admin).
alter table customers add column if not exists gated_access boolean not null default false;

-- ---- Seed from products.js (29 SKUs) ----
insert into products (id, sku, name, dosage, price, description, category, format, vial_size, in_stock, stock, is_kit, parent_id, vial_count, purity, badge, mw, half_life, recon_shelf_life, expiry, preorder_ship_date, visibility_tier, rail_policy, has_coa, image_url, published, sort_order) values
('glp3-10mg', 'OP-GLP3-10MG', 'GLP-3', '10mg', 69.95, 'Analytical reference material — triple-receptor GLP agonist (GLP-1 / GIP / glucagon), lyophilized. For in-vitro research and analytical use only; not for human or animal consumption.', 'GLPs', 'Lyophilized Powder', '2 mL Vial', true, 150, false, null, null, null, '"HERO"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 0),
('glp3-20mg', 'OP-GLP3-20MG', 'GLP-3', '20mg', 109.95, 'Analytical reference material — triple-receptor GLP agonist (GLP-1 / GIP / glucagon), lyophilized. For in-vitro research and analytical use only; not for human or animal consumption.', 'GLPs', 'Lyophilized Powder', '2 mL Vial', true, 100, false, null, null, null, '"HERO"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 1),
('glp3-10mg-kit', 'OP-GLP3-10MG-KIT', 'GLP-3 Kit (10x10mg)', '100mg total', 559.95, '10-vial analytical reference kit — triple-receptor GLP agonist (GLP-1 / GIP / glucagon), 10 mg per vial, lyophilized. For in-vitro research and analytical use only; not for human or animal consumption.', 'GLPs', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'glp3-10mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 2),
('glp3-20mg-kit', 'OP-GLP3-20MG-KIT', 'GLP-3 Kit (10x20mg)', '200mg total', 879.95, '10-vial analytical reference kit — triple-receptor GLP agonist (GLP-1 / GIP / glucagon), 20 mg per vial, lyophilized. For in-vitro research and analytical use only; not for human or animal consumption.', 'GLPs', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'glp3-20mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 3),
('glp1-10mg', 'OP-GLP1-10MG', 'GLP-1', '10mg', 74.95, 'Analytical reference material — GLP-1 receptor agonist peptide, lyophilized. For in-vitro research and analytical use only; not for human or animal consumption.', 'GLPs', 'Lyophilized Powder', '2 mL Vial', false, 0, false, null, null, null, '"NEW"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 4),
('glp1-10mg-kit', 'OP-GLP1-10MG-KIT', 'GLP-1 Kit (10x10mg)', '100mg total', 599.95, '10-vial analytical reference kit — GLP-1 receptor agonist, 10 mg per vial, lyophilized. For in-vitro research and analytical use only; not for human or animal consumption.', 'GLPs', 'Lyophilized Powder', '10 x 2 mL Vials', false, null, true, 'glp1-10mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 5),
('bpc-5mg', 'OP-BPC-5MG', 'BPC-157', '5mg', 29.95, 'Body Protection Compound-157. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '2 mL Vial', true, 100, false, null, null, null, null, null, null, null, null, null, 'public', 'all', true, null, true, 6),
('bpc-5mg-kit', 'OP-BPC-5MG-KIT', 'BPC-157 Kit (10x5mg)', '50mg total', 249.95, '10-vial kit — BPC-157 Body Protection Compound, 5mg each. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'bpc-5mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 7),
('bpc-10mg', 'OP-BPC-10MG', 'BPC-157', '10mg', 54.95, 'Body Protection Compound-157. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '2 mL Vial', true, 75, false, null, null, null, null, null, null, null, null, null, 'public', 'all', true, null, true, 8),
('bpc-10mg-kit', 'OP-BPC-10MG-KIT', 'BPC-157 Kit (10x10mg)', '100mg total', 449.95, '10-vial kit — BPC-157 Body Protection Compound, 10mg each. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'bpc-10mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 9),
('tb500-5mg', 'OP-TB500-5MG', 'TB-500', '5mg', 44.95, 'Thymosin Beta-4 Fragment. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '2 mL Vial', true, 75, false, null, null, null, null, null, null, null, null, null, 'public', 'all', true, null, true, 10),
('tb500-5mg-kit', 'OP-TB500-5MG-KIT', 'TB-500 Kit (10x5mg)', '50mg total', 374.95, '10-vial kit — TB-500 Thymosin Beta-4 Fragment, 5mg each. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'tb500-5mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 11),
('tb500-10mg', 'OP-TB500-10MG', 'TB-500', '10mg', 79.95, 'Thymosin Beta-4 Fragment. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '2 mL Vial', true, 50, false, null, null, null, null, null, null, null, null, null, 'public', 'all', true, null, true, 12),
('tb500-10mg-kit', 'OP-TB500-10MG-KIT', 'TB-500 Kit (10x10mg)', '100mg total', 674.95, '10-vial kit — TB-500 Thymosin Beta-4 Fragment, 10mg each. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'tb500-10mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 13),
('combo-70mg', 'OP-COMBO-70MG', 'BPC + TB + GHK-CU Combo', '70mg', 79.95, 'Triple peptide combination — BPC-157, TB-500, and GHK-CU. Lyophilized powder for research use.', 'Combos', 'Lyophilized Powder', '2 mL Vial', true, 40, false, null, null, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 14),
('combo-70mg-kit', 'OP-COMBO-70MG-KIT', 'BPC+TB+GHK Kit (10x70mg)', '700mg total', 674.95, '10-vial kit — Triple peptide combination, 70mg each. Lyophilized powder for research use.', 'Combos', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'combo-70mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 15),
('ipa-5mg', 'OP-IPA-5MG', 'Ipamorelin', '5mg', 29.95, 'Selective growth hormone secretagogue. Lyophilized powder for research use.', 'GH Peptides', 'Lyophilized Powder', '2 mL Vial', true, 75, false, null, null, 98, null, null, null, null, null, null, 'public', 'all', true, null, true, 16),
('ipa-5mg-kit', 'OP-IPA-5MG-KIT', 'Ipamorelin Kit (10x5mg)', '50mg total', 249.95, '10-vial kit — Ipamorelin GH Secretagogue, 5mg each. Lyophilized powder for research use.', 'GH Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'ipa-5mg', 10, 98, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 17),
('hgh-10iu', 'OP-HGH-10IU-KIT', 'HGH 191AA', '10IU (Kit of 10)', 239.95, '10-vial kit of HGH 191AA (somatropin), 10 IU per vial — 100 IU total per kit. The 191-amino-acid sequence matches the natural human GH structure (vs the synthetic 192aa variant), giving cleaner research signal and lower immunogenicity in published comparisons. Lyophilized powder; reconstitute with bacteriostatic water before research use.', 'GH Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', true, 25, false, null, 10, null, '"HERO"'::jsonb, '22.1 kDa', '~3-4 hours', '28 days at 2-8°C', '24 months at -20°C unopened', '2026-06-12', 'cohort', 'all', true, null, true, 18),
('hgh-24iu', 'OP-HGH-24IU-KIT', 'HGH 191AA', '24IU (Kit of 10)', 514.95, 'High-dose tier — 10-vial kit of HGH 191AA (somatropin), 24 IU per vial, 240 IU total per kit. Same 191-amino-acid sequence as the standard kit (matches natural human GH structure vs the synthetic 192aa variant) at a higher per-vial concentration for research requiring larger dosing. Lyophilized powder; reconstitute with bacteriostatic water before research use.', 'GH Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', false, 0, false, null, 10, null, '"NEW"'::jsonb, '22.1 kDa', '~3-4 hours', '28 days at 2-8°C', '24 months at -20°C unopened', null, 'cohort', 'all', true, null, true, 19),
('mt2-5mg', 'OP-MT2-5MG', 'MT-2', '5mg', 29.95, 'Melanotan II. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '2 mL Vial', true, 75, false, null, null, null, null, null, null, null, null, null, 'public', 'all', true, null, true, 20),
('mt2-5mg-kit', 'OP-MT2-5MG-KIT', 'MT-2 Kit (10x5mg)', '50mg total', 249.95, '10-vial kit — Melanotan II, 5mg each. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'mt2-5mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 21),
('motsc-10mg', 'OP-MOTSC-10MG', 'MOTS-C', '10mg', 64.99, 'Mitochondrial-derived peptide (16 amino acids) studied for metabolic regulation. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '2 mL Vial', false, 0, false, null, null, null, '"COMING SOON"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 22),
('motsc-10mg-kit', 'OP-MOTSC-10MG-KIT', 'MOTS-C Kit (10x10mg)', '100mg total', 539.95, '10-vial kit — MOTS-C mitochondrial peptide, 10mg each. Lyophilized powder for research use.', 'Peptides', 'Lyophilized Powder', '10 x 2 mL Vials', false, null, true, 'motsc-10mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 23),
('nad-500mg', 'OP-NAD-500MG', 'NAD+', '500mg', 57.95, 'Nicotinamide adenine dinucleotide. Lyophilized powder for research use.', 'Supplements', 'Lyophilized Powder', '2 mL Vial', true, 50, false, null, null, null, null, null, null, null, null, null, 'public', 'all', true, null, true, 24),
('nad-500mg-kit', 'OP-NAD-500MG-KIT', 'NAD+ Kit (10x500mg)', '5000mg total', 479.95, '10-vial kit — NAD+ Nicotinamide Adenine Dinucleotide, 500mg each. Lyophilized powder for research use.', 'Supplements', 'Lyophilized Powder', '10 x 2 mL Vials', true, null, true, 'nad-500mg', 10, null, '"BUNDLE"'::jsonb, null, null, null, null, null, 'public', 'all', true, null, true, 25),
('tadalafil-20mg', 'OP-TAD-20MG', 'Tadalafil', '20 mg/mL (30 mL)', 35.99, 'Tadalafil oral solution — 20 mg/mL in a 30 mL amber dropper bottle (600 mg total). Long-acting PDE5 inhibitor analog. For in-vitro research and laboratory use only.', 'Tinctures', 'Oral Solution', '30 mL Amber Dropper Bottle', false, 0, false, null, null, null, '"NEW"'::jsonb, null, null, null, null, null, 'cohort', 'zelle_crypto', false, null, true, 26),
('bac-water-10ml', 'OP-BAC-10ML', 'Bacteriostatic Water', '10 mL', 9.95, 'Sterile bacteriostatic water (0.9% benzyl alcohol preservative). Laboratory diluent for research use.', 'Supplies', 'Bacteriostatic Solution', '10 mL Vial', true, 40, false, null, null, null, null, null, null, null, null, null, 'cohort', 'all', true, null, true, 27),
('bac-water-30ml-hospira', 'OP-BAC-30ML', 'Bacteriostatic Water (Hospira)', '30 mL', 36.95, 'Genuine Hospira bacteriostatic water (0.9% benzyl alcohol preservative), 30 mL vial. Pharmaceutical-grade sterile laboratory diluent for research use.', 'Supplies', 'Bacteriostatic Solution', '30 mL Vial', true, 100, false, null, null, null, '"NEW"'::jsonb, null, null, null, null, null, 'cohort', 'all', true, null, true, 28)
on conflict (id) do nothing;
