-- Reclassify the "Supplements" category — 2026-07-22.
-- NoRamp/Stripe finding #6: the compliance policy states products are NOT
-- dietary supplements, but SKUs (e.g. NAD+) were categorized "Supplements" —
-- a direct contradiction an underwriter flagged. Move them to a research
-- category. The "Supplements" nav category + footer link are removed in code.
--
-- Review the SELECT first, then run the UPDATE.
--
--   SELECT id, name, category FROM products WHERE category = 'Supplements';
--
--   UPDATE products SET category = 'Ancillaries' WHERE category = 'Supplements';
--
-- (If any of these are better placed under 'Peptides' or 'GH Peptides', set
--  those individually instead — 'Ancillaries' is the safe default bucket.)
